hackmd:
  image: hackmdio/hackmd:latest
  environment:
    - HMD_PORT=80
    - LANG=ja_JP.UTF-8
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - HMD_GOOGLE_CLIENTID=${HMD_GOOGLE_CLIENTID}
    - HMD_GOOGLE_CLIENTSECRET=${HMD_GOOGLE_CLIENTSECRET}
  volumes:
    - ./hackmd/config.json:/hackmd/config.json
    - ./hackmd/.sequelizerc:/hackmd/.sequelizerc
  command: >
    sh -c "
      # default command
      /bin/bash /hackmd/docker-entrypoint.sh
    "
